version: "3.8"

services:

  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: db
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASSWORD
    ports: 
      - 1901:3306
      
  adminer:
    image: adminer
    restart: always
    ports:
       - 1902:8080