version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
    ports:
      - 1901:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 1902:8080
