version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
    ports:
      - 4601:5432
    networks:
      - postgres-net
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadminui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: EMAIL
      PGADMIN_DEFAULT_PASSWORD: PASSWORD
    ports:
      - 4602:80
    networks:
      - postgres-net

networks:
  postgres-net:
    driver: bridge