version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pdagminui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: EMAIL
      PGADMIN_DEFAULT_PASSWORD: PASSWORD
    ports:
      - 4601:80