version: "3.8"

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongo-db
    environment:
      - "MONGO_INITDB_ROOT_DATABASE=dockerdb"
      - "MONGO_INITDB_ROOT_USERNAME=a-username"
      - "MONGO_INITDB_ROOT_PASSWORD=a-secure-password"
    volumes:
      - "./seeds:/docker-entrypoint-initdb.d"
    ports:
      - 27017:27017
    networks:
      - mongodb-net

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 9000:8081
    environment:
      - "ME_CONFIG_MONGODB_SERVER=mongodb"
      - "ME_CONFIG_MONGODB_ENABLE_ADMIN=true"
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=a-username"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=a-secure-password"
    depends_on:
      - mongodb
    networks:
      - mongodb-net

networks:
  mongodb-net:
    driver: bridge