version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      - "MONGO_INITDB_ROOT_DATABASE=dockerdb"
      - "MONGO_INITDB_ROOT_USERNAME=USERNAME"
      - "MONGO_INITDB_ROOT_PASSWORD=PASSWORD"
    volumes:
      - "./seeds:/docker-entrypoint-initdb.d"
    ports:
      - 27017:27017
    networks:
      - mongodb-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 1902:8081
    environment:
      - "ME_CONFIG_MONGODB_SERVER=mongodb"
      - "ME_CONFIG_MONGODB_ENABLE_ADMIN=true"
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=USERNAME"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=PASSWORD"
    depends_on:
      - mongo
    networks:
      - mongodb-net
    

networks:
  mongodb-net:
    driver: bridge