version: "3.8"

services:
  sqlitebrowser:
    image: ghcr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - ./data:/config/data
    ports:
      - 1902:3000
    restart: unless-stopped